
grid_size = [5, 5, 5]

tiles = [
    [4, 0, 4],
    [3, 0, 4],
    [2, 0, 4],
    [1, 0, 4],
    [0, 0, 4],
    [0, 1, 4],
    [0, 2, 4],
    [0, 3, 4],
    [0, 4, 4],
    [0, 4, 3],
    [0, 4, 2],
    [0, 4, 1],
    [0, 4, 0],
    [1, 4, 0],
    [2, 4, 0],
    [3, 4, 0],
    [4, 4, 0],
    [4, 3, 0],
    [4, 2, 0],
    [4, 1, 0],
    [4, 0, 0],
    [4, 0, 1],
    [4, 0, 2],
    [4, 0, 3],
    [2, 2, 2],
    [1, 2, 2],
    [3, 2, 2],
    [2, 1, 2],
    [2, 3, 2],
    [2, 2, 1],
    [2, 2, 3],
    [4, 1, 4],
    [0, 0, 3],
    [3, 0, 0],
    [4, 4, 1],
    [1, 4, 4],
    [0, 3, 0],
    [4, 2, 4],
    [2, 0, 2],
    [2, 4, 4],
    [0, 2, 2],
    [4, 4, 2],
    [2, 2, 0],
    [0, 2, 0],
    [2, 4, 2],
    [2, 0, 0],
    [4, 2, 2],
    [0, 0, 2],
    [2, 2, 4]
]

[equalities]
bottom = [
    [4, 2, 4],
    [2, 0, 2]
]
top_left = [
    [2, 4, 4],
    [0, 2, 2]
]
top_right = [
    [4, 4, 2],
    [2, 2, 0]
]
top = [
    [0, 2, 0],
    [2, 4, 2]
]
bottom_left = [
    [2, 0, 0],
    [4, 2, 2]
]
bottom_right = [
    [0, 0, 2],
    [2, 2, 4]
]
